# Generated by Django 4.2.29 on 2026-03-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
