# Generated by Django 4.2.29 on 2026-03-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_file_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
